config/routes.rb
Rails.application.routes.draw do
  resources :bills ,except: [:edit ,:update] do
    # member do
    #   get 'bill_parts' , to: 'bills#bill_parts'
    # end
  end
  devise_for :users
  root 'static#home'
  get '/home',to: 'static#home' , as: 'home'
  get 'bill_parts' , to: 'bills#bill_parts'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :user , class_name: 'User', foreign_key: :user_id, primary_key: :id
  has_many :bill_parts, class_name:"BillPart", foreign_key: :bill_id , primary_key: :id, inverse_of: :bill , dependent: :delete_all

  # remember to uncomment
  validates_presence_of :event, :date, :location, :total_amount, :user_id

  accepts_nested_attributes_for :bill_parts,
  reject_if: lambda{|attrs| attrs['participant_id'].blank? || attrs['amount'].blank?}

  validates :total_amount, :numericality => { :greater_than_or_equal_to => 0 }

  # work around
  # There are always bill parts present on bill
  after_initialize do |bill|
    if bill.bill_parts.empty?
      User.order(:id).each{|user| bill.bill_parts.build(participant_id:user.id) }
    end
  end

  def get_total_bill_amount
    total_bill_amount = BillPart.where(bill_id: self.id).sum(:amount)
  end

  def get_number_of_participants
    number_of_participants = BillPart.where(bill_id: self.id).count
  end

  def get_split_per_head
    self.get_total_bill_amount / self.get_number_of_participants
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bill, only: [:show, :edit, :update, :destroy]
  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = current_user.bills.new
  end

  # GET /bills/1/edit
  # def edit
  # end

  # POST /bills
  # POST /bills.json
  def create
    @bill = current_user.bills.new(bill_params)
    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, success: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  # def update
  #   respond_to do |format|
  #     if @bill.update(bill_params)
  #       format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @bill }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @bill.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, success: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def bill_parts
    @bill_parts = BillPart.includes(:user,:bill)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.includes(:bill_parts,:user).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:event, :date, :location, :total_amount, :user_id , bill_parts_attributes: [:participant_id , :amount])
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= form_for bill do |form| %>
  <% if bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-6">
    <div class="form-group">
      <%= form.label :event %>
      <%= form.text_field :event, id: :bill_event %>
    </div>

    <div class="form-group">
      <%= form.label :date %>
      <%= form.date_select :date, id: :bill_date %>
    </div>

    <div class="form-group">
      <%= form.label :location %>
      <%= form.text_field :location, id: :bill_location %>
    </div>

    <div class="form-group">
      <%= form.label :total_amount %>
      <%= form.number_field :total_amount, id: :bill_total_amount , min: 0%>
    </div>
  </div>

  <div class="col-md-6">
    <p><strong>Enter bill contribution</strong></p>
    <p><strong>Enter 0 if participant was present but not paid</strong></p>
    <p><strong>Leave BLANK if participant was not present</strong></p>
    <div class="form-group">
      <%= form.fields_for :bill_parts do |bill_part_form|%>
        <div class="">
          <div class="form-group">
            <%= bill_part_form.label bill_part_form.object.user.name%>
            <%= bill_part_form.collection_select :participant_id , User.all ,:id , :name,{},{class:"hidden"}%>
          </div>
          <div class="form-group">
            <%= bill_part_form.number_field :amount, min:0%>
          </div>
        </div>
      <%end%>
    </div>
  </div>
  <div class="actions">
    <%= form.submit "Create Bill", class: "btn btn-primary btn-success"%>
  </div>
<% end %>

app/views/bills/bill_parts.html.erb
<p id="notice"><%= notice %></p>

<h1>Bills</h1>

<table class="table">
  <thead>
    <tr>
      <th>Bill ID</th>
      <th>User id</th>
      <th>User name</th>
      <th>Amount Paid</th>
    </tr>
  </thead>

  <tbody>
    <% @bill_parts.each do |bill_part| %>
      <tr>
        <td><%= bill_part.bill_id %></td>
        <td><%= bill_part.participant_id %></td>
        <td><%= bill_part.user.name %></td>
        <td><%= bill_part.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of all the bills</h1>
<table class="table">
  <thead>
    <tr>
      <th>Bill id</th>
      <th>Event</th>
      <th>Date</th>
      <th>Location</th>
      <th>Total amount</th>
      <th>Added by</th>
      <th>Per head</th>
      <th>Added </th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%=bill.id%></td>
        <td><%= bill.event %></td>
        <td><%= bill.date %></td>
        <td><%= bill.location %></td>
        <td><%= bill.total_amount %></td>
        <td><%= bill.user.name %></td>
        <td><%= bill.get_split_per_head%></td>
        <td><%= time_ago_in_words(bill.created_at) + ' ago' %></td>
        <td><%= link_to 'Details', bill  , class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-primary btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%=create_new_bill_button%>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form', bill: @bill %>

<br/>

<%=create_back_button%>

app/views/bills/show.html.erb
<h2><strong>Bill Details</strong></h2>
<div class="container">
  <p>
    <strong>Event:</strong>
    <%= @bill.event %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= @bill.date %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= @bill.location %>
  </p>

  <p>
    <strong>Total amount:</strong>
    <%= @bill.total_amount %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @bill.user_id %>
  </p>
</div>

<h2><strong>Amount paid by each participant for this bill</strong></h2>

<div class="container">
  <p>
    <%@bill.bill_parts.each do |bill_part|%>
      <p>
        <%=bill_part.user.name%> : <%=bill_part.amount%>
      </p>
    <%end%>
  </p>
</div>
<br/>
<%=create_back_button%>